#include "libretro.h"
#include "godot_cpp/classes/global_constants.hpp"

retro_key godotKeyToRetroKey(godot::Key key) {
    switch (key) {
        case godot::Key::KEY_UNKNOWN:
            return RETROK_UNKNOWN;
        case godot::Key::KEY_BACKSPACE:
            return RETROK_BACKSPACE;
        case godot::Key::KEY_TAB:
            return RETROK_TAB;
        case godot::Key::KEY_CLEAR:
            return RETROK_CLEAR;
        case godot::Key::KEY_ENTER:
            return RETROK_RETURN;
        case godot::Key::KEY_PAUSE:
            return RETROK_PAUSE;
        case godot::Key::KEY_ESCAPE:
            return RETROK_ESCAPE;
        case godot::Key::KEY_SPACE:
            return RETROK_SPACE;
        case godot::Key::KEY_EXCLAM:
            return RETROK_EXCLAIM;
        case godot::Key::KEY_QUOTEDBL:
            return RETROK_QUOTEDBL;
        case godot::Key::KEY_NUMBERSIGN:
            return RETROK_HASH;
        case godot::Key::KEY_DOLLAR:
            return RETROK_DOLLAR;
        case godot::Key::KEY_AMPERSAND:
            return RETROK_AMPERSAND;
        case godot::Key::KEY_APOSTROPHE:
            return RETROK_QUOTE;
        case godot::Key::KEY_PARENLEFT:
            return RETROK_LEFTPAREN;
        case godot::Key::KEY_PARENRIGHT:
            return RETROK_RIGHTPAREN;
        case godot::Key::KEY_ASTERISK:
            return RETROK_ASTERISK;
        case godot::Key::KEY_PLUS:
            return RETROK_PLUS;
        case godot::Key::KEY_COMMA:
            return RETROK_COMMA;
        case godot::Key::KEY_MINUS:
            return RETROK_MINUS;
        case godot::Key::KEY_PERIOD:
            return RETROK_PERIOD;
        case godot::Key::KEY_SLASH:
            return RETROK_SLASH;
        case godot::Key::KEY_0:
            return RETROK_0;
        case godot::Key::KEY_1:
            return RETROK_1;
        case godot::Key::KEY_2:
            return RETROK_2;
        case godot::Key::KEY_3:
            return RETROK_3;
        case godot::Key::KEY_4:
            return RETROK_4;
        case godot::Key::KEY_5:
            return RETROK_5;
        case godot::Key::KEY_6:
            return RETROK_6;
        case godot::Key::KEY_7:
            return RETROK_7;
        case godot::Key::KEY_8:
            return RETROK_8;
        case godot::Key::KEY_9:
            return RETROK_9;
        case godot::Key::KEY_COLON:
            return RETROK_COLON;
        case godot::Key::KEY_SEMICOLON:
            return RETROK_SEMICOLON;
        case godot::Key::KEY_LESS:
            return RETROK_LESS;
        case godot::Key::KEY_EQUAL:
            return RETROK_EQUALS;
        case godot::Key::KEY_GREATER:
            return RETROK_GREATER;
        case godot::Key::KEY_QUESTION:
            return RETROK_QUESTION;
        case godot::Key::KEY_AT:
            return RETROK_AT;
        case godot::Key::KEY_BRACKETLEFT:
            return RETROK_LEFTBRACKET;
        case godot::Key::KEY_BACKSLASH:
            return RETROK_BACKSLASH;
        case godot::Key::KEY_BRACKETRIGHT:
            return RETROK_RIGHTBRACKET;
        case godot::Key::KEY_ASCIICIRCUM:
            return RETROK_CARET;
        case godot::Key::KEY_UNDERSCORE:
            return RETROK_UNDERSCORE;
        case godot::Key::KEY_QUOTELEFT:
            return RETROK_BACKQUOTE;
        case godot::Key::KEY_A:
            return RETROK_a;
        case godot::Key::KEY_B:
            return RETROK_b;
        case godot::Key::KEY_C:
            return RETROK_c;
        case godot::Key::KEY_D:
            return RETROK_d;
        case godot::Key::KEY_E:
            return RETROK_e;
        case godot::Key::KEY_F:
            return RETROK_f;
        case godot::Key::KEY_G:
            return RETROK_g;
        case godot::Key::KEY_H:
            return RETROK_h;
        case godot::Key::KEY_I:
            return RETROK_i;
        case godot::Key::KEY_J:
            return RETROK_j;
        case godot::Key::KEY_K:
            return RETROK_k;
        case godot::Key::KEY_L:
            return RETROK_l;
        case godot::Key::KEY_M:
            return RETROK_m;
        case godot::Key::KEY_N:
            return RETROK_n;
        case godot::Key::KEY_O:
            return RETROK_o;
        case godot::Key::KEY_P:
            return RETROK_p;
        case godot::Key::KEY_Q:
            return RETROK_q;
        case godot::Key::KEY_R:
            return RETROK_r;
        case godot::Key::KEY_S:
            return RETROK_s;
        case godot::Key::KEY_T:
            return RETROK_t;
        case godot::Key::KEY_U:
            return RETROK_u;
        case godot::Key::KEY_V:
            return RETROK_v;
        case godot::Key::KEY_W:
            return RETROK_w;
        case godot::Key::KEY_X:
            return RETROK_x;
        case godot::Key::KEY_Y:
            return RETROK_y;
        case godot::Key::KEY_Z:
            return RETROK_z;
        case godot::Key::KEY_BRACELEFT:
            return RETROK_LEFTBRACE;
        case godot::Key::KEY_BAR:
            return RETROK_BAR;
        case godot::Key::KEY_BRACERIGHT:
            return RETROK_RIGHTBRACE;
        case godot::Key::KEY_ASCIITILDE:
            return RETROK_TILDE;
        case godot::Key::KEY_DELETE:
            return RETROK_DELETE;
        case godot::Key::KEY_KP_MULTIPLY:
            return RETROK_KP_MULTIPLY;
        case godot::Key::KEY_KP_DIVIDE:
            return RETROK_KP_DIVIDE;
        case godot::Key::KEY_KP_SUBTRACT:
            return RETROK_KP_MINUS;
        case godot::Key::KEY_KP_PERIOD:
            return RETROK_KP_PERIOD;
        case godot::Key::KEY_KP_ADD:
            return RETROK_KP_PLUS;
        case godot::Key::KEY_KP_0:
            return RETROK_KP0;
        case godot::Key::KEY_KP_1:
            return RETROK_KP1;
        case godot::Key::KEY_KP_2:
            return RETROK_KP2;
        case godot::Key::KEY_KP_3:
            return RETROK_KP3;
        case godot::Key::KEY_KP_4:
            return RETROK_KP4;
        case godot::Key::KEY_KP_5:
            return RETROK_KP5;
        case godot::Key::KEY_KP_6:
            return RETROK_KP6;
        case godot::Key::KEY_KP_7:
            return RETROK_KP7;
        case godot::Key::KEY_KP_8:
            return RETROK_KP8;
        case godot::Key::KEY_KP_9:
            return RETROK_KP9;
        case godot::Key::KEY_KP_ENTER:
            return RETROK_KP_ENTER;
        // case godot::Key::KEY_KP_EQUALS:
        //     return RETROK_KP_EQUALS;
        case godot::Key::KEY_UP:
            return RETROK_UP;
        case godot::Key::KEY_DOWN:
            return RETROK_DOWN;
        case godot::Key::KEY_RIGHT:
            return RETROK_RIGHT;
        case godot::Key::KEY_LEFT:
            return RETROK_LEFT;
        case godot::Key::KEY_INSERT:
            return RETROK_INSERT;
        case godot::Key::KEY_HOME:
            return RETROK_HOME;
        case godot::Key::KEY_END:
            return RETROK_END;
        case godot::Key::KEY_PAGEUP:
            return RETROK_PAGEUP;
        case godot::Key::KEY_PAGEDOWN:
            return RETROK_PAGEDOWN;
        case godot::Key::KEY_F1:
            return RETROK_F1;
        case godot::Key::KEY_F2:
            return RETROK_F2;
        case godot::Key::KEY_F3:
            return RETROK_F3;
        case godot::Key::KEY_F4:
            return RETROK_F4;
        case godot::Key::KEY_F5:
            return RETROK_F5;
        case godot::Key::KEY_F6:
            return RETROK_F6;
        case godot::Key::KEY_F7:
            return RETROK_F7;
        case godot::Key::KEY_F8:
            return RETROK_F8;
        case godot::Key::KEY_F9:
            return RETROK_F9;
        case godot::Key::KEY_F10:
            return RETROK_F10;
        case godot::Key::KEY_F11:
            return RETROK_F11;
        case godot::Key::KEY_F12:
            return RETROK_F12;
        case godot::Key::KEY_F13:
            return RETROK_F13;
        case godot::Key::KEY_F14:
            return RETROK_F14;
        case godot::Key::KEY_F15:
            return RETROK_F15;
        case godot::Key::KEY_NUMLOCK:
            return RETROK_NUMLOCK;
        case godot::Key::KEY_CAPSLOCK:
            return RETROK_CAPSLOCK;
        case godot::Key::KEY_SCROLLLOCK:
            return RETROK_SCROLLOCK;
        case godot::Key::KEY_SHIFT:
            return RETROK_RSHIFT;
        case godot::Key::KEY_CTRL:
            return RETROK_RCTRL;
        case godot::Key::KEY_META:
            return RETROK_RMETA;
        case godot::Key::KEY_ALT:
            return RETROK_RALT;
        case godot::Key::KEY_MENU:
            return RETROK_MENU;
        case godot::Key::KEY_HELP:
            return RETROK_HELP;
        case godot::Key::KEY_PRINT:
            return RETROK_PRINT;
        case godot::Key::KEY_SYSREQ:
            return RETROK_SYSREQ;
        default:
            return RETROK_UNKNOWN;
    }
}
